name: Deploy React SPA

on:
  push:
    branches:
      - main   # trigger only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Build React app
      - name: Build React app
        run: |
          npm ci
          npm run build

      # 4. Copy build folder to VPS
      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/*"
          target: "/home/dolano/docker-data/nginx/html/apps/brave-pink"
